apiVersion: ocm.mobb.redhat.com/v1alpha1
kind: MachinePool
metadata:
  name: spot
spec:
  clusterName: "dscott"
  minimumNodesPerZone: 1
  maximumNodesPerZone: 1
  instanceType: m5.xlarge
  labels:
    this: that
  aws:
    spotInstances:
      enabled: true
      maximumPrice: 5